version: '2'
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.5.1"
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
